---
title: "Final Project"
author: "Yunqiu Yao, Cenai Zhang, Yutian Mu, Murrel Pereira"
date: "12/9/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(forcats)
library(boot)
```

```{r}
### clean the date
gh = read_excel("./GHProject_Dataset.xlsx") %>% 
  clean_names %>% 
  separate(admitdtm, c("admit_dow","date","year"), ",") %>% 
  mutate(date = trimws(date, "left")) %>% 
  separate(date,c("month","sdate")," ") %>% 
  mutate(month = as.numeric(match(month,month.name)),
         sdate = as.numeric(sdate),
         year = as.numeric(year),
         admit_date = paste(month, sdate, year, sep="-"),
         admit_date = as.Date(admit_date, "%m-%d-%Y")) %>%
  select(-c(sdate,year,month)) %>% 
  mutate(log_losday = log(losdays2))

### remove the duplicate visits
gh = gh[order(gh$admit_date),]
gh_unique <- gh[!duplicated(gh$patientid),]

### recode the levels of categorical variables
gh_tidy = gh_unique %>% 
  mutate(mews = as.factor(ifelse(mews <= 1, "normal", ifelse(mews <= 3, "increase caution", ifelse(mews <= 5, "further deterioration", "immediate action required")))),
         cindex = as.factor(ifelse(cindex == 0, "normal", ifelse(cindex <= 2, "mild", ifelse(cindex <= 4, "moderate", "severe")))),
         is30dayreadmit = as.factor(is30dayreadmit),
         icu_flag = as.factor(icu_flag)) %>% 
  select(log_losday, losdays2, patientid, visitid, admit_date, admit_dow, everything(), -loshours, -facilityname, -facilityzip, -postalcode)
```


<<<<<<< HEAD
<<<<<<< HEAD
## Select the variables and fit the linear model
=======
<<<<<<< HEAD
## Select the variables and fit the linear model
=======
=======
>>>>>>> parent of 9b1761a... Changes after merge
```{r}
#Descriptive Statistics
summary(gh_tidy)

<<<<<<< HEAD
=======
gh_tidy$gender[gh_tidy$gender == "Male"] = 0
gh_tidy$gender[gh_tidy$gender == "Female"] = 1

>>>>>>> parent of 9b1761a... Changes after merge
par(mfrow = c(1, 2))
hist(gh_tidy$losdays2, main = "Length of Stay")
hist(gh_tidy$log_losday, main = "Log Length of Stay")

par(mfrow = c(1, 2))
barplot(table(gh_tidy$admit_dow), las = 2, main = "Day of Week Frequency")
barplot(table(gh_tidy$is30dayreadmit), las = 1, main = "Is patient 30 day readmit?")
barplot(table(gh_tidy$mews), las = 2, main = "Modified Early Warning Score (MEWS)")
barplot(table(gh_tidy$cindex), las = 2, main = "Charlson comorbidity index (CCI)")


barplot(table(gh_tidy$icu_flag), main = "If patient visited ICU")
barplot(table(gh_tidy$gender), main = "Gender")
barplot(table(gh_tidy$race), las =2, main = "Race Frequency")
barplot(table(gh_tidy$religion), las = 2, main = "Religion Frequency")
barplot(table(gh_tidy$maritalstatus), las = 2, main = "Marital Status Frequency")
barplot(table(gh_tidy$insurancetype), las = 1, main = "Insurance Type")

<<<<<<< HEAD

=======
>>>>>>> parent of 9b1761a... Changes after merge
par(mfrow = c(3, 3))
hist(gh_tidy$evisit, main = "ER visits in past 6 months")
hist(gh_tidy$ageyear, main ="Age Histogram") #might need a log transformation
hist(gh_tidy$bmi, main = "BMI")
hist(gh_tidy$bpsystolic, main = "BP Systolic") #120 - 140 mmHg normal range
hist(gh_tidy$bpdiastolic, main = "BP Diastolic") #80 -90 mmHg normal range
hist(gh_tidy$o2sat, main = "O2 Saturation") #Normal is  <100 - check for outliers
hist(gh_tidy$temperature, main = "Temperature") #Normal range is 36.1 C - 37.2 C - check for outliers; can go upto 42C
hist(gh_tidy$heartrate, main = "Heart Rate") #40 - 100 beats per minute
hist(gh_tidy$respirationrate, main = "Respiration Rate") #12 - 25 breaths per minute in normal adult


<<<<<<< HEAD
=======
gh_tidy$temperature[gh_tidy$temperature < 36] <- NA
gh_tidy$temperature[gh_tidy$temperature > 42] <- NA
gh_tidy$o2sat[gh_tidy$o2sat > 100] <- NA

>>>>>>> parent of 9b1761a... Changes after merge

par(mfrow = c(1, 2))
hist(gh_tidy$o2sat, main = "O2 Saturation") #Normal is  <100 - check for outliers
hist(gh_tidy$temperature, main = "Temperature")

class(gh_tidy$gender) <- "binary"
class(gh_tidy$icu_flag) <- "binary"
class(gh_tidy$is30dayreadmit) <- "binary"

```

<<<<<<< HEAD
>>>>>>> a786538b01c5ae7d0c7859167824368e69cf35b1
>>>>>>> 362e85057e9f36c34bee3a7808cf2a0b9b17eb15
=======
>>>>>>> parent of 9b1761a... Changes after merge
```{r}
gh_reg = gh_tidy %>%
  select(log_losday:insurancetype, -losdays2, -patientid, -visitid, -admit_date) %>%
  na.omit() %>% 
  mutate(cindex = fct_relevel(cindex, "normal"),
         mews = fct_relevel(mews, "normal"))


#fit models
model <- lm(gh_reg$log_losday~ ., data = gh_reg)
summary(model)
```

```{r model_building}
#backward
backward = step(model, direction = 'backward')
summary(lm(formula = log_losday ~ is30dayreadmit + mews + cindex + evisit + ageyear + insurancetype, data = gh_reg))

#both 
stepwise = step(model, direction = 'both')
summary(lm(formula = log_losday ~ is30dayreadmit + mews + cindex + evisit + ageyear + insurancetype, data = gh_reg))
#both and backward are same.
#is30dayreadmit1+mews(*3)+cindex(*3)+evisit+ageyear+insurance(*2)

#forward
forward = step(model, direction = 'forward')
summary(lm(formula = gh_reg$log_losday ~ admit_dow + is30dayreadmit + mews + cindex + evisit + icu_flag + ageyear + gender + race + religion + maritalstatus + insurancetype, data = gh_reg))

#criterion-based 
best <- function(model, ...) 
{
  subsets <- leaps::regsubsets(formula(model), model.frame(model), ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

best(model, nbest=1)
#we choose size=8. is30dayreadmit1+mews immediate action required+cindex moderate+cindex severe+evisit+ageyear+maritalstatus single+insurancetype private
```

```{r diagnosis}
fit = lm(log_losday ~ is30dayreadmit + mews + cindex + evisit + ageyear + insurancetype, data=gh_reg)
par(mfrow = c(2, 2))
plot(fit)
```

```{r validation}
#LOOCV--unbiased estimate of test error
glm.fit<-glm(log_losday ~ is30dayreadmit + mews + cindex + evisit + ageyear + insurancetype, data=gh_reg)
cv.err<-cv.glm(gh_reg,glm.fit)
cv.err$delta   
<<<<<<< HEAD
<<<<<<< HEAD

=======
#The two delta values should be similar: we use the first one.The second value is bias corrected.
>>>>>>> parent of 9b1761a... Changes after merge
```

<<<<<<< HEAD

=======
<<<<<<< HEAD

```
Delta value is the average mean-squared error. According to the lecture, the two delta values should be similar. We use the first one, and the second value is bias corrected.


>>>>>>> 362e85057e9f36c34bee3a7808cf2a0b9b17eb15
### Bootstrap
=======
>>>>>>> parent of 9b1761a... Changes after merge
```{r bootstrap}
=======
#The two delta values should be similar: we use the first one.The second value is bias corrected.

#bootstrap
>>>>>>> a786538b01c5ae7d0c7859167824368e69cf35b1
gh_reg %>% 
  modelr::bootstrap(n = 100) %>% 
  mutate(models = map(strap, ~lm(gh_reg$log_losday ~ is30dayreadmit + cindex + evisit + 
    ageyear + gender + maritalstatus + insurancetype + bpsystolic + 
    o2sat + temperature + heartrate + respirationrate + bpdiastolic, 
    data = .x)),
         results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest() %>% 
  group_by(term) %>% 
  summarize(boot_se = sd(estimate)) 
```

